# Appveyor Build Scrip https://www.appveyor.com

version: 0.1.1.{build}

image: Visual Studio 2017

platform: Any CPU

configuration: Release

install:
  # MonoGame
  - ps: (new-object net.webclient).DownloadFile('http://www.monogame.net/releases/v3.6/MonoGameSetup.exe', 'C:\MonoGameSetup.exe')
  - ps: Invoke-Command -ScriptBlock {C:\MonoGameSetup.exe /S /v/qn}

before_build:
  # the NuGet packages had not been restored.
  - ps: nuget restore ToxicUnited.sln

build:
  parallel: true
  project: ToxicUnited.sln

  # artifacts
artifacts: 
  - path: ToxicUnited\bin\Release\
    name: ToxicUnited-Release-$(APPVEYOR_BUILD_VERSION) 
    type: zip 
  - path: ToxicUnited\bin\Debug\
  name: ToxicUnited-Debug-$(APPVEYOR_BUILD_VERSION) 
  type: zip  